### ISSUE TITLE
develop 브랜치 추가 건의

### ISSUE THREAD

**Issue by kimjooyoon** [angryOil/todoList#4]
main 은 develop 에서 작업된 내용을 PR 을 통해 반영하는 것은 어떨까요?

다음 장점이 있습니다

- ci/cd 적용 시 파이프라인 효휼성 증가
- 기능개발, 배포에 대한 책임 분리

**Comment by kimjooyoon** [comment]
@angryOil 
default 브랜치는 develop 으로 하는게 좋은 것 같아요
결국 개발자가 pr 을 할때 자동 완성이 되고 자주 보는 것도 develop 브랜치가 될 듯합니다

**Comment by angryOil** [comment]
조만간 추가 하겠습니다.

구조는 main(prod) <- stage(stage) <- dev(dev server) 로 만들예정입니다. 

규칙은 
1. 가장 최신 dev 브랜치로 풀 받기 
2. fix를 제외한 feat은 dev로 pr 
입니다.

**Comment by angryOil** [comment]
브랜치 추가 완료
