### ISSUE TITLE
[bug] test code 실행 실패

### ISSUE THREAD

**Issue by kimjooyoon** [angryOil/todoList#5]
repository/todoRepository_test.go 165 라인 코드가 실패합니다

**Comment by kimjooyoon** [comment]
@angryOil 모든 테스트를 동시에 실행하면 문제가 되는 것 같습니다

**Comment by angryOil** [comment]
> @angryOil모든 테스트를 동시에 실행하면 문제가 되는 것 같습니다.

확인 해본결과 getList메소드에는 데이터가 존재한다면 실패할수밖에없는 상황이고
데이터 자체를 index 1에 넣어서 테스트를 하다보니 실행전에 초기화로 id번에 테스트 데이터를
넣던지 아니면 mockRepo를 사용해야 할거같습니다.
현재 init은 넣어놓았고 getList 테스트는 현재로서는 mockRepo를 만들지 않는이상 
성공하게 만들방법이 따로 없어보입니다.

**Comment by kimjooyoon** [comment]
> > @angryOil모든 테스트를 동시에 실행하면 문제가 되는 것 같습니다.
> 
> 확인 해본결과 getList메소드에는 데이터가 존재한다면 실패할수밖에없는 상황이고 데이터 자체를 index 1에 넣어서 테스트를 하다보니 실행전에 초기화로 id번에 테스트 데이터를 넣던지 아니면 mockRepo를 사용해야 할거같습니다. 현재 init은 넣어놓았고 getList 테스트는 현재로서는 mockRepo를 만들지 않는이상 성공하게 만들방법이 따로 없어보입니다.

현재 transaction 을 따로 발급하고 있지 않고
repository 에서 bun.db 를 그대로 사용하고 있습니다

repository 에서 bun.IDB 로 변경한 이후 test 가 실행되기 전에 transaction 을 주입하고 
test 실행 이후 해당 트랜잭션을 롤백하는 방법을 사용하면 될것 같습니다

예제 pr 올려보겠습니다
